apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nodejs-app-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: nodejs-app
  replicas: 4
  template:
    metadata:
      labels:
        app:  nodejs-app
    spec:
      containers:
      - name:  nodejs-app
        image:  node:20-alpine3.20
        command: ["sleep","100000"]

      