apiVersion: v1
kind: Service
metadata:
  name: LoadBalancer-service
  namespace: default
spec:
  selector:
    app: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  externalTrafficPolicy: Local
  type: LoadBalancer
 