apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres-db
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  postgres-db-deployment
spec:
  selector:
    matchLabels:
      app: postgres-db
  replicas: 1
  template:
    metadata:
      labels:
        app:  postgres-db
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  postgres-db
        image:  postgres:17.0-alpine3.20
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: postgres-config
        volumeMounts:
          - mountPath: /var/lib/postgressql/data
            name: postgres-volume
      
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        